name: Deploy to itch.io
on:
  push:
    branches:
      - main
  workflow_dispatch:    # Manual trigger via UI
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: dont-get-swatted
          ITCH_USER: haydondo
          PACKAGE: src
          VERSION: ${{ github.sha }}
